normalize: True
model: 'models/SuperPoint_Coco/final_round/superpoint/superpoint_coco_15-XX.h5'
picklefile: 'HPatches/hpatches-v.pickle'
export_name: 'exports/superpoint_hpatches_descriptors/superpoint/v'
h5_export_name: 'exports/superpoint_hpatches_descriptors/superpoint/v/descriptors.h5'
alteration: 'v'  # 'all' 'i' 'v'
dataset: 'hpatches'
valid_border_margin: 4
preprocessing:
    resize: [480, 640]  # False for coco [480, 640]
batch_size: 50
eval_batch_size: 50
learning_rate: 0.001
detection_threshold: 0.001 # 1/65
nms: 8 # 8
top_k: 1000
grid_size: 8
homography_adaptation:
    num: 0
    aggregation: 'sum'
    filter_counts: 10
    homographies:
        translation: True
        rotation: True
        scaling: True
        perspective: True
        scaling_amplitude: 0.1
        perspective_amplitude_x: 0.2
        perspective_amplitude_y: 0.2
        patch_ratio: 0.85
        max_angle: 1.57
        allow_artifacts: False
eval_iter: -1
seed: 1