normalize: True
log_dir: 'tensorboard/MagicPoint_Shapes'
picklefile: 'synthetic_shapes.pickle'
checkpoint_model: 'models/MagicPoint_Shapes/magicpoint_ss_50-{epoch:02d}.h5'
checkpoint_weights: 'models/MagicPoint_Shapes/magicpoint_ss_weights_50-{epoch:02d}.h5'
checkpoint_optimizer: 'models/MagicPoint_Shapes/magicpoint_ss_optimizer_50-{epoch:02d}.pickle'
model_visual: '/home/ubuntu/data/magicpoint.png'
train_batch_size: 33
eval_batch_size: 50
learning_rate: 0.001
epochs: 50 # 40
steps_per_epoch: 2000 # ceil(train size (66000) / batch size)
validation_steps: 33 # validation size / eval batch size
validation_size: 1650 # 500
detection_threshold: 0.001 # 1/65
nms: 4
seed: 0
top_k: 0
pretrained_model: False
preprocessing:
  resize: [120, 160]
augmentation:
  photometric:
    enable: True
    primitives: ['random_brightness', 'random_contrast', 'additive_speckle_noise', 'additive_gaussian_noise',
                 'additive_shade', 'motion_blur' ]
    params:
      random_brightness: {max_abs_change: 75}
      random_contrast: {strength_range: [0.3, 1.8]}
      additive_gaussian_noise: {stddev_range: [0, 15]}
      additive_speckle_noise: {prob_range: [0, 0.0035]}
      additive_shade:
        transparency_range: [-0.5, 0.8]
        kernel_size_range: [50, 100]
      motion_blur: {max_kernel_size: 7}
    random_order: True
  homographic:
    enable: True
    params:
      translation: True
      rotation: True
      scaling: True
      perspective: True
      scaling_amplitude: 0.2
      perspective_amplitude_x: 0.2
      perspective_amplitude_y: 0.2
      patch_ratio: 0.8
      max_angle: 1.57  # 3.14
      allow_artifacts: True
      translation_overflow: 0.05
    valid_border_margin: 2