homographies:
    translation: True
    rotation: True
    scaling: False
    perspective: False
    scaling_amplitude: 0.1
    perspective_amplitude_x: 0.05
    perspective_amplitude_y: 0.05
    patch_ratio: 0.9
    max_angle: 0.2617 #3.14
preprocessing:
    resize: [240, 320]